### ISSUE TITLE
Globaler Buchhalter

### ISSUE THREAD

**Issue by hummbaeri** [schas2/Project1#4]
Wie weiss Szene, dass Spieler alle Vorbedingungen für Sieg etc getroffen hat?

**Comment by SoullessStone** [comment]
asfsdfasf

**Comment by schas2** [comment]
@SoullessStone :+1:

**Comment by SoullessStone** [comment]
Dokumentiert wurde das Ganze hier: https://github.com/schas2/Project1/wiki/Scene-change
(siehe Problem 2)
